### ISSUE TITLE
Grouping issue

### ISSUE THREAD

**Issue by nonozg** [leonreucher/grandma3-patch2pdf#1]
Plugin works just fine if u have fixtures out of groups in patch window, but if I got em in groups, plugin exporting only that groups, plugin dont see fixtures inside. but good job 👍 

<img width="1086" alt="Screenshot 2024-05-16 at 10 39 21" src="https://github.com/leonreucher/grandma3-patch2pdf/assets/74436770/81ba66e6-b46f-4517-a01b-fd5ff836ea48">

**Comment by leonreucher** [comment]
Thank you for creating this issue - I added support for groups, so they should now get exported successfully. Please give it a try and report if it worked for you @nonozg
