### ISSUE TITLE
localize variables

### ISSUE THREAD

**Issue by jefffarrow** [leonreucher/grandma3-patch2pdf#10]
https://github.com/leonreucher/grandma3-patch2pdf/blame/6c6a44fe8e74137308a23c176e92ea4bd77d7b71/patch2pdf.lua#L631-L640

The following variables can be localized to optimize scope in a multi plugin environment (lines 631 to 640)

p, helv, bold, pages, page

**Comment by leonreucher** [comment]
Although I am not exactly sure what you mean by a multi plugin environment - I've changed the according lines to localize the variable definition.
Thanks for the hint!

**Comment by jefffarrow** [comment]
By multi plugin environment, I mean that a grandMA  user may have multiple
plugins in their file.  If you declare the variables p, pages, page as
Global and another plugin also uses a Global of the same name then you
might get unexpected results; as global variables are visible to the entire
environment, not just the individual plugin.  Local is the way to go,
unless you want something to persist in the environment.  If you do want a
persistent variable, it should have a very unique name to prevent it from
accidentally interacting with other plugins.  So "p" could become "P_p2p".
Also be aware that all variables get null when you run ReloadUI

**Comment by leonreucher** [comment]
Thank you very much for the detailed explanation - got it now!
